// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trippin.API.Data;

#nullable disable

namespace Trippin.API.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260429112428_AddOAuthFields")]
    partial class AddOAuthFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Trippin.API.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOutDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConfirmationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Trippin.API.Models.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AverageCostPerDay")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("BestTimeToVisit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Highlights")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPopular")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageCostPerDay = 180m,
                            BestTimeToVisit = "April–October",
                            Category = "beach",
                            City = "Oia",
                            Country = "Greece",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Iconic whitewashed villages, caldera sunsets, and Aegean charm.",
                            Highlights = "Caldera views|Sunset in Oia|Volcanic beaches",
                            ImageUrl = "https://images.unsplash.com/photo-1613395877344-13d4c79d428e?w=1200",
                            IsDeleted = false,
                            IsPopular = true,
                            Latitude = 36.4619,
                            Longitude = 25.375800000000002,
                            Name = "Santorini",
                            Tags = "islands,sunset,wine",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1613395877344-13d4c79d428e?w=400"
                        },
                        new
                        {
                            Id = 6,
                            AverageCostPerDay = 350m,
                            BestTimeToVisit = "November–April",
                            Category = "beach",
                            City = "Malé Atolls",
                            Country = "Maldives",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Overwater villas and crystal-clear Indian Ocean lagoons.",
                            Highlights = "House reef snorkeling|Sunset dhoni|Spa rituals",
                            ImageUrl = "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=1200",
                            IsDeleted = false,
                            IsPopular = true,
                            Latitude = 3.2027999999999999,
                            Longitude = 73.220699999999994,
                            Name = "Maldives",
                            Tags = "luxury,diving,relaxation",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=400"
                        },
                        new
                        {
                            Id = 7,
                            AverageCostPerDay = 60m,
                            BestTimeToVisit = "April–October",
                            Category = "beach",
                            City = "Ubud",
                            Country = "Indonesia",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Terraced rice paddies, sacred temples, and surf beaches.",
                            Highlights = "Uluwatu Temple|Tegallalang Rice Terrace|Seminyak Beach",
                            ImageUrl = "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=1200",
                            IsDeleted = false,
                            IsPopular = true,
                            Latitude = -8.3405000000000005,
                            Longitude = 115.092,
                            Name = "Bali",
                            Tags = "surfing,temples,rice-terraces",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=400"
                        },
                        new
                        {
                            Id = 8,
                            AverageCostPerDay = 55m,
                            BestTimeToVisit = "November–March",
                            Category = "beach",
                            City = "Phuket",
                            Country = "Thailand",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Turquoise Andaman Sea, limestone karsts, and Thai street food.",
                            Highlights = "Phi Phi Islands|Patong Beach|Big Buddha",
                            ImageUrl = "https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?w=1200",
                            IsDeleted = false,
                            IsPopular = true,
                            Latitude = 7.8803999999999998,
                            Longitude = 98.392300000000006,
                            Name = "Phuket",
                            Tags = "islands,nightlife,food",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?w=400"
                        },
                        new
                        {
                            Id = 9,
                            AverageCostPerDay = 220m,
                            BestTimeToVisit = "May–September",
                            Category = "beach",
                            City = "Positano",
                            Country = "Italy",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Pastel cliffside villages cascading into the Mediterranean.",
                            Highlights = "Path of the Gods|Ravello Gardens|Limoncello tasting",
                            ImageUrl = "https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?w=1200",
                            IsDeleted = false,
                            IsPopular = false,
                            Latitude = 40.633299999999998,
                            Longitude = 14.6029,
                            Name = "Amalfi Coast",
                            Tags = "coastline,food,romance",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?w=400"
                        },
                        new
                        {
                            Id = 10,
                            AverageCostPerDay = 120m,
                            BestTimeToVisit = "December–April",
                            Category = "beach",
                            City = "Cancún",
                            Country = "Mexico",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Caribbean beaches, Mayan ruins, and cenote swimming.",
                            Highlights = "Chichén Itzá|Isla Mujeres|Cenote Ik Kil",
                            ImageUrl = "https://images.unsplash.com/photo-1552074284-5e88ef1aef18?w=1200",
                            IsDeleted = false,
                            IsPopular = true,
                            Latitude = 21.161899999999999,
                            Longitude = -86.851500000000001,
                            Name = "Cancún",
                            Tags = "ruins,cenotes,nightlife",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1552074284-5e88ef1aef18?w=400"
                        },
                        new
                        {
                            Id = 11,
                            AverageCostPerDay = 80m,
                            BestTimeToVisit = "June–October",
                            Category = "beach",
                            City = "Stone Town",
                            Country = "Tanzania",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Spice island with white sand, coral reefs, and historic Stone Town.",
                            Highlights = "Stone Town|Nungwi Beach|Spice tour",
                            ImageUrl = "https://images.unsplash.com/photo-1586861203927-800a5acdcc4e?w=1200",
                            IsDeleted = false,
                            IsPopular = false,
                            Latitude = -6.1658999999999997,
                            Longitude = 39.202599999999997,
                            Name = "Zanzibar",
                            Tags = "spices,snorkeling,history",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1586861203927-800a5acdcc4e?w=400"
                        },
                        new
                        {
                            Id = 12,
                            AverageCostPerDay = 250m,
                            BestTimeToVisit = "April–May, Sep–Nov",
                            Category = "beach",
                            City = "Lahaina",
                            Country = "United States",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Volcanic craters, whale watching, and the Road to Hana.",
                            Highlights = "Haleakalā Sunrise|Road to Hana|Molokini Snorkeling",
                            ImageUrl = "https://images.unsplash.com/photo-1542259009477-d625272157b7?w=1200",
                            IsDeleted = false,
                            IsPopular = false,
                            Latitude = 20.798400000000001,
                            Longitude = -156.33189999999999,
                            Name = "Maui",
                            Tags = "volcanoes,surfing,whales",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1542259009477-d625272157b7?w=400"
                        },
                        new
                        {
                            Id = 13,
                            AverageCostPerDay = 300m,
                            BestTimeToVisit = "April–May, Oct–Nov",
                            Category = "beach",
                            City = "Mahé",
                            Country = "Seychelles",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Granite boulders, giant tortoises, and pristine Indian Ocean coves.",
                            Highlights = "Anse Source d'Argent|Vallée de Mai|Giant tortoises",
                            ImageUrl = "https://images.unsplash.com/photo-1589979481223-deb893043163?w=1200",
                            IsDeleted = false,
                            IsPopular = false,
                            Latitude = -4.6795999999999998,
                            Longitude = 55.491999999999997,
                            Name = "Seychelles",
                            Tags = "luxury,nature,snorkeling",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1589979481223-deb893043163?w=400"
                        },
                        new
                        {
                            Id = 4,
                            AverageCostPerDay = 150m,
                            BestTimeToVisit = "April–June, Sep–Oct",
                            Category = "city",
                            City = "Barcelona",
                            Country = "Spain",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Gaudí architecture, Mediterranean beaches, and vibrant nightlife.",
                            Highlights = "Sagrada Família|Gothic Quarter|Barceloneta",
                            ImageUrl = "https://images.unsplash.com/photo-1583422409516-2895a77efded?w=1200",
                            IsDeleted = false,
                            IsPopular = true,
                            Latitude = 41.385100000000001,
                            Longitude = 2.1734,
                            Name = "Barcelona",
                            Tags = "architecture,food,beach",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1583422409516-2895a77efded?w=400"
                        },
                        new
                        {
                            Id = 14,
                            AverageCostPerDay = 130m,
                            BestTimeToVisit = "March–May, Oct–Nov",
                            Category = "city",
                            City = "Tokyo",
                            Country = "Japan",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Neon-lit metropolis blending ultramodern and traditional.",
                            Highlights = "Shibuya Crossing|Senso-ji Temple|Tsukiji Market",
                            ImageUrl = "https://images.unsplash.com/photo-1540959733332-eab8343a890d?w=1200",
                            IsDeleted = false,
                            IsPopular = true,
                            Latitude = 35.676200000000001,
                            Longitude = 139.65029999999999,
                            Name = "Tokyo",
                            Tags = "food,technology,anime",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1540959733332-eab8343a890d?w=400"
                        },
                        new
                        {
                            Id = 15,
                            AverageCostPerDay = 200m,
                            BestTimeToVisit = "April–June, Sep–Oct",
                            Category = "city",
                            City = "Paris",
                            Country = "France",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "The City of Light — art, fashion, cuisine, and the Eiffel Tower.",
                            Highlights = "Eiffel Tower|Louvre Museum|Montmartre",
                            ImageUrl = "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1200",
                            IsDeleted = false,
                            IsPopular = true,
                            Latitude = 48.8566,
                            Longitude = 2.3521999999999998,
                            Name = "Paris",
                            Tags = "art,food,romance",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=400"
                        },
                        new
                        {
                            Id = 16,
                            AverageCostPerDay = 280m,
                            BestTimeToVisit = "April–June, Sep–Nov",
                            Category = "city",
                            City = "New York",
                            Country = "United States",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "The city that never sleeps — Broadway, Central Park, and pizza.",
                            Highlights = "Central Park|Times Square|Statue of Liberty",
                            ImageUrl = "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=1200",
                            IsDeleted = false,
                            IsPopular = true,
                            Latitude = 40.712800000000001,
                            Longitude = -74.006,
                            Name = "New York",
                            Tags = "broadway,food,shopping",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=400"
                        },
                        new
                        {
                            Id = 17,
                            AverageCostPerDay = 200m,
                            BestTimeToVisit = "November–March",
                            Category = "city",
                            City = "Dubai",
                            Country = "United Arab Emirates",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Futuristic skyline, desert safaris, and luxury shopping.",
                            Highlights = "Burj Khalifa|Dubai Mall|Desert safari",
                            ImageUrl = "https://images.unsplash.com/photo-1512453913507-d187c340770a?w=1200",
                            IsDeleted = false,
                            IsPopular = true,
                            Latitude = 25.204799999999999,
                            Longitude = 55.270800000000001,
                            Name = "Dubai",
                            Tags = "luxury,shopping,desert",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1512453913507-d187c340770a?w=400"
                        },
                        new
                        {
                            Id = 18,
                            AverageCostPerDay = 220m,
                            BestTimeToVisit = "May–September",
                            Category = "city",
                            City = "London",
                            Country = "United Kingdom",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Royal palaces, world-class museums, and afternoon tea.",
                            Highlights = "Tower of London|British Museum|West End",
                            ImageUrl = "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=1200",
                            IsDeleted = false,
                            IsPopular = false,
                            Latitude = 51.507399999999997,
                            Longitude = -0.1278,
                            Name = "London",
                            Tags = "history,theatre,pubs",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=400"
                        },
                        new
                        {
                            Id = 19,
                            AverageCostPerDay = 180m,
                            BestTimeToVisit = "February–April",
                            Category = "city",
                            City = "Singapore",
                            Country = "Singapore",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Garden city-state with hawker food, Marina Bay, and Sentosa.",
                            Highlights = "Marina Bay Sands|Gardens by the Bay|Hawker centres",
                            ImageUrl = "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=1200",
                            IsDeleted = false,
                            IsPopular = false,
                            Latitude = 1.3521000000000001,
                            Longitude = 103.8198,
                            Name = "Singapore",
                            Tags = "food,gardens,clean",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=400"
                        },
                        new
                        {
                            Id = 20,
                            AverageCostPerDay = 70m,
                            BestTimeToVisit = "April–May, Sep–Nov",
                            Category = "city",
                            City = "Istanbul",
                            Country = "Turkey",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Where East meets West — bazaars, mosques, and Bosphorus cruises.",
                            Highlights = "Hagia Sophia|Grand Bazaar|Bosphorus cruise",
                            ImageUrl = "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=1200",
                            IsDeleted = false,
                            IsPopular = false,
                            Latitude = 41.008200000000002,
                            Longitude = 28.978400000000001,
                            Name = "Istanbul",
                            Tags = "history,bazaars,food",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=400"
                        },
                        new
                        {
                            Id = 21,
                            AverageCostPerDay = 160m,
                            BestTimeToVisit = "April–June, Sep–Oct",
                            Category = "city",
                            City = "Rome",
                            Country = "Italy",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Eternal City of emperors — Colosseum, Vatican, and gelato.",
                            Highlights = "Colosseum|Vatican Museums|Trevi Fountain",
                            ImageUrl = "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=1200",
                            IsDeleted = false,
                            IsPopular = false,
                            Latitude = 41.902799999999999,
                            Longitude = 12.4964,
                            Name = "Rome",
                            Tags = "history,food,art",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=400"
                        },
                        new
                        {
                            Id = 22,
                            AverageCostPerDay = 190m,
                            BestTimeToVisit = "September–November",
                            Category = "city",
                            City = "Sydney",
                            Country = "Australia",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Harbour icons, golden beaches, and laid-back Aussie culture.",
                            Highlights = "Sydney Opera House|Bondi Beach|Harbour Bridge",
                            ImageUrl = "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=1200",
                            IsDeleted = false,
                            IsPopular = false,
                            Latitude = -33.8688,
                            Longitude = 151.20930000000001,
                            Name = "Sydney",
                            Tags = "beaches,opera,surfing",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=400"
                        },
                        new
                        {
                            Id = 23,
                            AverageCostPerDay = 40m,
                            BestTimeToVisit = "October–March",
                            Category = "city",
                            City = "Mumbai",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Bollywood, street food, colonial grandeur, and the Arabian Sea.",
                            Highlights = "Gateway of India|Marine Drive|Dharavi tour",
                            ImageUrl = "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=1200",
                            IsDeleted = false,
                            IsPopular = false,
                            Latitude = 19.076000000000001,
                            Longitude = 72.877700000000004,
                            Name = "Mumbai",
                            Tags = "food,bollywood,history",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=400"
                        },
                        new
                        {
                            Id = 24,
                            AverageCostPerDay = 170m,
                            BestTimeToVisit = "October–December",
                            Category = "city",
                            City = "Hong Kong",
                            Country = "China",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Dizzying skyline, dim sum, and Victoria Peak views.",
                            Highlights = "Victoria Peak|Star Ferry|Temple Street Market",
                            ImageUrl = "https://images.unsplash.com/photo-1536599018102-9f803c029b22?w=1200",
                            IsDeleted = false,
                            IsPopular = false,
                            Latitude = 22.319299999999998,
                            Longitude = 114.1694,
                            Name = "Hong Kong",
                            Tags = "food,skyline,shopping",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1536599018102-9f803c029b22?w=400"
                        },
                        new
                        {
                            Id = 2,
                            AverageCostPerDay = 140m,
                            BestTimeToVisit = "March–May, Oct–Nov",
                            Category = "cultural",
                            City = "Kyoto",
                            Country = "Japan",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Temples, tea houses, and timeless Japanese culture.",
                            Highlights = "Fushimi Inari|Arashiyama bamboo|Gion district",
                            ImageUrl = "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200",
                            IsDeleted = false,
                            IsPopular = true,
                            Latitude = 35.011600000000001,
                            Longitude = 135.7681,
                            Name = "Kyoto",
                            Tags = "temples,tea,gardens",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=400"
                        },
                        new
                        {
                            Id = 25,
                            AverageCostPerDay = 60m,
                            BestTimeToVisit = "March–May, Sep–Nov",
                            Category = "cultural",
                            City = "Marrakech",
                            Country = "Morocco",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Medina souks, riads, and the Atlas Mountains backdrop.",
                            Highlights = "Jemaa el-Fnaa|Majorelle Garden|Atlas Mountains",
                            ImageUrl = "https://images.unsplash.com/photo-1489749798305-4fea3ae63d43?w=1200",
                            IsDeleted = false,
                            IsPopular = false,
                            Latitude = 31.6295,
                            Longitude = -7.9810999999999996,
                            Name = "Marrakech",
                            Tags = "souks,riads,spices",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1489749798305-4fea3ae63d43?w=400"
                        },
                        new
                        {
                            Id = 26,
                            AverageCostPerDay = 50m,
                            BestTimeToVisit = "May–September",
                            Category = "cultural",
                            City = "Cusco",
                            Country = "Peru",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Gateway to Machu Picchu and Inca heritage in the Andes.",
                            Highlights = "Machu Picchu|Sacred Valley|Rainbow Mountain",
                            ImageUrl = "https://images.unsplash.com/photo-1526392060635-9d6019884377?w=1200",
                            IsDeleted = false,
                            IsPopular = false,
                            Latitude = -13.532,
                            Longitude = -71.967500000000001,
                            Name = "Cusco",
                            Tags = "ruins,andes,history",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1526392060635-9d6019884377?w=400"
                        },
                        new
                        {
                            Id = 27,
                            AverageCostPerDay = 25m,
                            BestTimeToVisit = "October–March",
                            Category = "cultural",
                            City = "Varanasi",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "India's spiritual heart — Ganges ghats and ancient rituals.",
                            Highlights = "Ganga Aarti|Dashashwamedh Ghat|Sarnath",
                            ImageUrl = "https://images.unsplash.com/photo-1561361058-c24cecae35ca?w=1200",
                            IsDeleted = false,
                            IsPopular = false,
                            Latitude = 25.317599999999999,
                            Longitude = 82.9739,
                            Name = "Varanasi",
                            Tags = "spiritual,ganges,temples",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1561361058-c24cecae35ca?w=400"
                        },
                        new
                        {
                            Id = 28,
                            AverageCostPerDay = 45m,
                            BestTimeToVisit = "October–April",
                            Category = "cultural",
                            City = "Cairo",
                            Country = "Egypt",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Pyramids, pharaohs, and the mighty Nile.",
                            Highlights = "Great Pyramids|Egyptian Museum|Khan el-Khalili",
                            ImageUrl = "https://images.unsplash.com/photo-1572252009286-268acec5ca0a?w=1200",
                            IsDeleted = false,
                            IsPopular = false,
                            Latitude = 30.0444,
                            Longitude = 31.235700000000001,
                            Name = "Cairo",
                            Tags = "pyramids,history,nile",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1572252009286-268acec5ca0a?w=400"
                        },
                        new
                        {
                            Id = 29,
                            AverageCostPerDay = 80m,
                            BestTimeToVisit = "March–May, Sep–Nov",
                            Category = "cultural",
                            City = "Wadi Musa",
                            Country = "Jordan",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Rose-red city carved into desert cliffs by the Nabataeans.",
                            Highlights = "The Treasury|The Monastery|Siq canyon",
                            ImageUrl = "https://images.unsplash.com/photo-1579606032821-4e6161c81c86?w=1200",
                            IsDeleted = false,
                            IsPopular = false,
                            Latitude = 30.328499999999998,
                            Longitude = 35.444400000000002,
                            Name = "Petra",
                            Tags = "archaeology,desert,hiking",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1579606032821-4e6161c81c86?w=400"
                        },
                        new
                        {
                            Id = 30,
                            AverageCostPerDay = 30m,
                            BestTimeToVisit = "November–March",
                            Category = "cultural",
                            City = "Siem Reap",
                            Country = "Cambodia",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Ancient Angkor temples rising from tropical jungle.",
                            Highlights = "Angkor Wat|Bayon Temple|Ta Prohm",
                            ImageUrl = "https://images.unsplash.com/photo-1600000418916-3ef26d36c01b?w=1200",
                            IsDeleted = false,
                            IsPopular = false,
                            Latitude = 13.367100000000001,
                            Longitude = 103.84480000000001,
                            Name = "Siem Reap",
                            Tags = "temples,jungle,history",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1600000418916-3ef26d36c01b?w=400"
                        },
                        new
                        {
                            Id = 31,
                            AverageCostPerDay = 100m,
                            BestTimeToVisit = "April–June, Sep–Oct",
                            Category = "cultural",
                            City = "Athens",
                            Country = "Greece",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Birthplace of democracy with the Acropolis watching over.",
                            Highlights = "Acropolis|Plaka|Ancient Agora",
                            ImageUrl = "https://images.unsplash.com/photo-1555993539-1b2e5c58e0d7?w=1200",
                            IsDeleted = false,
                            IsPopular = false,
                            Latitude = 37.983800000000002,
                            Longitude = 23.727499999999999,
                            Name = "Athens",
                            Tags = "acropolis,philosophy,food",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1555993539-1b2e5c58e0d7?w=400"
                        },
                        new
                        {
                            Id = 3,
                            AverageCostPerDay = 200m,
                            BestTimeToVisit = "June–Sep, Dec–Mar",
                            Category = "mountains",
                            City = "Banff",
                            Country = "Canada",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Rocky Mountain peaks, turquoise lakes, and alpine adventure.",
                            Highlights = "Lake Louise|Moraine Lake|Banff Gondola",
                            ImageUrl = "https://images.unsplash.com/photo-1503614472-8c93d56e92ce?w=1200",
                            IsDeleted = false,
                            IsPopular = true,
                            Latitude = 51.178400000000003,
                            Longitude = -115.57080000000001,
                            Name = "Banff",
                            Tags = "hiking,lakes,winter",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1503614472-8c93d56e92ce?w=400"
                        },
                        new
                        {
                            Id = 32,
                            AverageCostPerDay = 300m,
                            BestTimeToVisit = "June–Sep, Dec–Mar",
                            Category = "mountains",
                            City = "Interlaken",
                            Country = "Switzerland",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Snow-capped peaks, chocolate, and precision railways.",
                            Highlights = "Jungfrau|Lauterbrunnen Valley|Glacier Express",
                            ImageUrl = "https://images.unsplash.com/photo-1530122037265-83aee0480052?w=1200",
                            IsDeleted = false,
                            IsPopular = true,
                            Latitude = 46.686300000000003,
                            Longitude = 7.8632,
                            Name = "Swiss Alps",
                            Tags = "skiing,trains,chocolate",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1530122037265-83aee0480052?w=400"
                        },
                        new
                        {
                            Id = 33,
                            AverageCostPerDay = 120m,
                            BestTimeToVisit = "October–March",
                            Category = "mountains",
                            City = "El Chaltén",
                            Country = "Argentina",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Raw wilderness of glaciers, granite spires, and steppe.",
                            Highlights = "Perito Moreno Glacier|Torres del Paine|Fitz Roy",
                            ImageUrl = "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1200",
                            IsDeleted = false,
                            IsPopular = false,
                            Latitude = -49.331499999999998,
                            Longitude = -72.885999999999996,
                            Name = "Patagonia",
                            Tags = "trekking,glaciers,wildlife",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=400"
                        },
                        new
                        {
                            Id = 34,
                            AverageCostPerDay = 40m,
                            BestTimeToVisit = "June–September",
                            Category = "mountains",
                            City = "Leh",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "High-altitude desert with monasteries and Pangong Lake.",
                            Highlights = "Pangong Lake|Nubra Valley|Khardung La",
                            ImageUrl = "https://images.unsplash.com/photo-1544735716-ea9ef0a14fb4?w=1200",
                            IsDeleted = false,
                            IsPopular = false,
                            Latitude = 34.1526,
                            Longitude = 77.577100000000002,
                            Name = "Leh-Ladakh",
                            Tags = "monasteries,passes,lakes",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1544735716-ea9ef0a14fb4?w=400"
                        },
                        new
                        {
                            Id = 35,
                            AverageCostPerDay = 180m,
                            BestTimeToVisit = "June–Sep, Dec–Mar",
                            Category = "mountains",
                            City = "Cortina",
                            Country = "Italy",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Dramatic pink-hued peaks and alpine meadows in northern Italy.",
                            Highlights = "Tre Cime|Seceda|Lago di Braies",
                            ImageUrl = "https://images.unsplash.com/photo-1501854140801-ce89f857b5b7?w=1200",
                            IsDeleted = false,
                            IsPopular = false,
                            Latitude = 46.410200000000003,
                            Longitude = 11.844099999999999,
                            Name = "Dolomites",
                            Tags = "via-ferrata,skiing,hiking",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1501854140801-ce89f857b5b7?w=400"
                        },
                        new
                        {
                            Id = 5,
                            AverageCostPerDay = 175m,
                            BestTimeToVisit = "Year-round",
                            Category = "adventure",
                            City = "Queenstown",
                            Country = "New Zealand",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Adventure capital with bungee, skiing, and fjord scenery.",
                            Highlights = "Milford Sound|Skyline Gondola|Jet boating",
                            ImageUrl = "https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=1200",
                            IsDeleted = false,
                            IsPopular = false,
                            Latitude = -45.031199999999998,
                            Longitude = 168.6626,
                            Name = "Queenstown",
                            Tags = "bungee,ski,lake",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=400"
                        },
                        new
                        {
                            Id = 36,
                            AverageCostPerDay = 220m,
                            BestTimeToVisit = "June–Aug, Sep–Mar for aurora",
                            Category = "adventure",
                            City = "Reykjavik",
                            Country = "Iceland",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Fire and ice — volcanoes, glaciers, geysers, and northern lights.",
                            Highlights = "Golden Circle|Blue Lagoon|Northern Lights",
                            ImageUrl = "https://images.unsplash.com/photo-1504829857797-deb22ed9158a?w=1200",
                            IsDeleted = false,
                            IsPopular = true,
                            Latitude = 64.146600000000007,
                            Longitude = -21.942599999999999,
                            Name = "Iceland",
                            Tags = "aurora,glaciers,geysers",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1504829857797-deb22ed9158a?w=400"
                        },
                        new
                        {
                            Id = 37,
                            AverageCostPerDay = 90m,
                            BestTimeToVisit = "December–April",
                            Category = "adventure",
                            City = "La Fortuna",
                            Country = "Costa Rica",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Rainforests, zip-lines, sloths, and Pacific surf.",
                            Highlights = "Arenal Volcano|Monteverde|Manuel Antonio",
                            ImageUrl = "https://images.unsplash.com/photo-1518259102261-b40117eabbc8?w=1200",
                            IsDeleted = false,
                            IsPopular = false,
                            Latitude = 10.469900000000001,
                            Longitude = -84.642700000000005,
                            Name = "Costa Rica",
                            Tags = "wildlife,rainforest,surfing",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1518259102261-b40117eabbc8?w=400"
                        },
                        new
                        {
                            Id = 38,
                            AverageCostPerDay = 150m,
                            BestTimeToVisit = "May–September",
                            Category = "adventure",
                            City = "Kruger",
                            Country = "South Africa",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Big Five safaris on the African savanna.",
                            Highlights = "Big Five game drives|Panorama Route|Bush walks",
                            ImageUrl = "https://images.unsplash.com/photo-1516426122078-f30e1c35ee33?w=1200",
                            IsDeleted = false,
                            IsPopular = false,
                            Latitude = -24.011299999999999,
                            Longitude = 31.485399999999998,
                            Name = "Kruger",
                            Tags = "safari,wildlife,big-five",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1516426122078-f30e1c35ee33?w=400"
                        },
                        new
                        {
                            Id = 39,
                            AverageCostPerDay = 250m,
                            BestTimeToVisit = "June–November",
                            Category = "adventure",
                            City = "Puerto Ayora",
                            Country = "Ecuador",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Darwin's living laboratory — giant tortoises and marine iguanas.",
                            Highlights = "Giant tortoises|Blue-footed boobies|Snorkeling",
                            ImageUrl = "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200",
                            IsDeleted = false,
                            IsPopular = false,
                            Latitude = -0.74319999999999997,
                            Longitude = -90.303799999999995,
                            Name = "Galápagos",
                            Tags = "wildlife,diving,endemic",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400"
                        },
                        new
                        {
                            Id = 40,
                            AverageCostPerDay = 35m,
                            BestTimeToVisit = "Oct–Nov, Mar–May",
                            Category = "adventure",
                            City = "Kathmandu",
                            Country = "Nepal",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Himalayan trekking, Everest Base Camp, and Buddhist serenity.",
                            Highlights = "Everest Base Camp|Annapurna Circuit|Boudhanath",
                            ImageUrl = "https://images.unsplash.com/photo-1544735716-392fe2489fcd?w=1200",
                            IsDeleted = false,
                            IsPopular = false,
                            Latitude = 27.717199999999998,
                            Longitude = 85.323999999999998,
                            Name = "Nepal",
                            Tags = "trekking,everest,temples",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1544735716-392fe2489fcd?w=400"
                        },
                        new
                        {
                            Id = 41,
                            AverageCostPerDay = 230m,
                            BestTimeToVisit = "May–September",
                            Category = "nature",
                            City = "Bergen",
                            Country = "Norway",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Dramatic sea-carved valleys and midnight sun.",
                            Highlights = "Geirangerfjord|Trolltunga|Flåm Railway",
                            ImageUrl = "https://images.unsplash.com/photo-1507272931001-fc06c17866f4?w=1200",
                            IsDeleted = false,
                            IsPopular = false,
                            Latitude = 60.391300000000001,
                            Longitude = 5.3220999999999998,
                            Name = "Norwegian Fjords",
                            Tags = "fjords,midnight-sun,hiking",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1507272931001-fc06c17866f4?w=400"
                        },
                        new
                        {
                            Id = 42,
                            AverageCostPerDay = 200m,
                            BestTimeToVisit = "June–October",
                            Category = "nature",
                            City = "Cairns",
                            Country = "Australia",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "World's largest coral reef teeming with marine life.",
                            Highlights = "Outer reef diving|Whitehaven Beach|Glass-bottom boat",
                            ImageUrl = "https://images.unsplash.com/photo-1582967788606-a171c7e0f7fc?w=1200",
                            IsDeleted = false,
                            IsPopular = false,
                            Latitude = -16.918600000000001,
                            Longitude = 145.77809999999999,
                            Name = "Great Barrier Reef",
                            Tags = "diving,coral,marine",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1582967788606-a171c7e0f7fc?w=400"
                        },
                        new
                        {
                            Id = 43,
                            AverageCostPerDay = 70m,
                            BestTimeToVisit = "April–June, Sep–Nov",
                            Category = "nature",
                            City = "Göreme",
                            Country = "Turkey",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Fairy chimneys, cave hotels, and hot-air balloon sunrises.",
                            Highlights = "Hot-air balloons|Underground cities|Göreme Open-Air Museum",
                            ImageUrl = "https://images.unsplash.com/photo-1526048598645-62b7c9ee6c7d?w=1200",
                            IsDeleted = false,
                            IsPopular = true,
                            Latitude = 38.643099999999997,
                            Longitude = 34.828699999999998,
                            Name = "Cappadocia",
                            Tags = "balloons,caves,history",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1526048598645-62b7c9ee6c7d?w=400"
                        },
                        new
                        {
                            Id = 44,
                            AverageCostPerDay = 100m,
                            BestTimeToVisit = "June–November",
                            Category = "nature",
                            City = "Manaus",
                            Country = "Brazil",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Earth's greatest rainforest — pink dolphins and canopy walks.",
                            Highlights = "Canopy walk|Pink river dolphins|Indigenous villages",
                            ImageUrl = "https://images.unsplash.com/photo-1596587483932-df0c1e6c3a31?w=1200",
                            IsDeleted = false,
                            IsPopular = false,
                            Latitude = -3.1190000000000002,
                            Longitude = -60.021700000000003,
                            Name = "Amazon",
                            Tags = "jungle,wildlife,river",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1596587483932-df0c1e6c3a31?w=400"
                        },
                        new
                        {
                            Id = 45,
                            AverageCostPerDay = 150m,
                            BestTimeToVisit = "May–September",
                            Category = "nature",
                            City = "West Yellowstone",
                            Country = "United States",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Geysers, bison herds, and prismatic hot springs.",
                            Highlights = "Old Faithful|Grand Prismatic Spring|Lamar Valley",
                            ImageUrl = "https://images.unsplash.com/photo-1529439322271-42e2b71b9ec0?w=1200",
                            IsDeleted = false,
                            IsPopular = false,
                            Latitude = 44.427999999999997,
                            Longitude = -110.5885,
                            Name = "Yellowstone",
                            Tags = "geysers,wildlife,national-park",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1529439322271-42e2b71b9ec0?w=400"
                        },
                        new
                        {
                            Id = 46,
                            AverageCostPerDay = 100m,
                            BestTimeToVisit = "March–October",
                            Category = "city",
                            City = "Lisbon",
                            Country = "Portugal",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Pastel-tiled hills, tram 28, and pastéis de nata.",
                            Highlights = "Belém Tower|Alfama|Time Out Market",
                            ImageUrl = "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200",
                            IsDeleted = false,
                            IsPopular = false,
                            Latitude = 38.722299999999997,
                            Longitude = -9.1393000000000004,
                            Name = "Lisbon",
                            Tags = "food,trams,tiles",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=400"
                        },
                        new
                        {
                            Id = 47,
                            AverageCostPerDay = 80m,
                            BestTimeToVisit = "April–June, Sep–Oct",
                            Category = "city",
                            City = "Prague",
                            Country = "Czech Republic",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Gothic spires, Charles Bridge, and affordable beer.",
                            Highlights = "Charles Bridge|Old Town Square|Prague Castle",
                            ImageUrl = "https://images.unsplash.com/photo-1541849546-216549ae216d?w=1200",
                            IsDeleted = false,
                            IsPopular = false,
                            Latitude = 50.075499999999998,
                            Longitude = 14.437799999999999,
                            Name = "Prague",
                            Tags = "beer,architecture,history",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1541849546-216549ae216d?w=400"
                        },
                        new
                        {
                            Id = 48,
                            AverageCostPerDay = 100m,
                            BestTimeToVisit = "November–April",
                            Category = "beach",
                            City = "Tulum",
                            Country = "Mexico",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Bohemian beach town with Mayan clifftop ruins.",
                            Highlights = "Tulum Ruins|Gran Cenote|Sian Ka'an Biosphere",
                            ImageUrl = "https://images.unsplash.com/photo-1504681869696-d977211a5f4c?w=1200",
                            IsDeleted = false,
                            IsPopular = false,
                            Latitude = 20.211400000000001,
                            Longitude = -87.465400000000002,
                            Name = "Tulum",
                            Tags = "ruins,cenotes,yoga",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1504681869696-d977211a5f4c?w=400"
                        },
                        new
                        {
                            Id = 49,
                            AverageCostPerDay = 35m,
                            BestTimeToVisit = "October–March",
                            Category = "cultural",
                            City = "Jaipur",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "The Pink City — forts, palaces, and Rajasthani colour.",
                            Highlights = "Amber Fort|Hawa Mahal|City Palace",
                            ImageUrl = "https://images.unsplash.com/photo-1477587458883-47145ed94245?w=1200",
                            IsDeleted = false,
                            IsPopular = false,
                            Latitude = 26.912400000000002,
                            Longitude = 75.787300000000002,
                            Name = "Jaipur",
                            Tags = "forts,palaces,textiles",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1477587458883-47145ed94245?w=400"
                        },
                        new
                        {
                            Id = 50,
                            AverageCostPerDay = 130m,
                            BestTimeToVisit = "May–September",
                            Category = "city",
                            City = "Dubrovnik",
                            Country = "Croatia",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Walled Old Town on the Adriatic — the real King's Landing.",
                            Highlights = "City Walls walk|Lokrum Island|Cable car",
                            ImageUrl = "https://images.unsplash.com/photo-1555990793-da11153b2473?w=1200",
                            IsDeleted = false,
                            IsPopular = false,
                            Latitude = 42.650700000000001,
                            Longitude = 18.0944,
                            Name = "Dubrovnik",
                            Tags = "walls,adriatic,history",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1555990793-da11153b2473?w=400"
                        });
                });

            modelBuilder.Entity("Trippin.API.Models.Itinerary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAiGenerated")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.HasIndex("UserId");

                    b.ToTable("Itineraries");
                });

            modelBuilder.Entity("Trippin.API.Models.ItineraryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DayNumber")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DestinationId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<decimal?>("EstimatedCost")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ItineraryId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("ItineraryId");

                    b.ToTable("ItineraryItems");
                });

            modelBuilder.Entity("Trippin.API.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<int>("HelpfulVotes")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Photos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Trippin.API.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Budget")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TravelersCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("Trippin.API.Models.TripDestination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DaysToSpend")
                        .HasColumnType("int");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<int>("VisitOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("TripId", "DestinationId")
                        .IsUnique();

                    b.ToTable("TripDestinations");
                });

            modelBuilder.Entity("Trippin.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthProvider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GitHubId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MicrosoftId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Trippin.API.Models.Booking", b =>
                {
                    b.HasOne("Trippin.API.Models.Trip", "Trip")
                        .WithMany("Bookings")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trippin.API.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trippin.API.Models.Itinerary", b =>
                {
                    b.HasOne("Trippin.API.Models.Trip", "Trip")
                        .WithMany("Itineraries")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trippin.API.Models.User", "User")
                        .WithMany("Itineraries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trippin.API.Models.ItineraryItem", b =>
                {
                    b.HasOne("Trippin.API.Models.Destination", "Destination")
                        .WithMany("ItineraryItems")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Trippin.API.Models.Itinerary", "Itinerary")
                        .WithMany("Items")
                        .HasForeignKey("ItineraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Itinerary");
                });

            modelBuilder.Entity("Trippin.API.Models.Review", b =>
                {
                    b.HasOne("Trippin.API.Models.Destination", "Destination")
                        .WithMany("Reviews")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Trippin.API.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trippin.API.Models.Trip", b =>
                {
                    b.HasOne("Trippin.API.Models.User", "User")
                        .WithMany("Trips")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trippin.API.Models.TripDestination", b =>
                {
                    b.HasOne("Trippin.API.Models.Destination", "Destination")
                        .WithMany("TripDestinations")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Trippin.API.Models.Trip", "Trip")
                        .WithMany("TripDestinations")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Trippin.API.Models.Destination", b =>
                {
                    b.Navigation("ItineraryItems");

                    b.Navigation("Reviews");

                    b.Navigation("TripDestinations");
                });

            modelBuilder.Entity("Trippin.API.Models.Itinerary", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Trippin.API.Models.Trip", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Itineraries");

                    b.Navigation("TripDestinations");
                });

            modelBuilder.Entity("Trippin.API.Models.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Itineraries");

                    b.Navigation("Reviews");

                    b.Navigation("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
